version: "3.5"
services:

  kafka-gen:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka-gen
    container_name: kafka-gen
    volumes:
      - ./scripts/create_cluster_id.sh:/tmp/create_cluster_id.sh
      - ./clusterID:/tmp/clusterID
    command: "bash -c '/tmp/create_cluster_id.sh'"

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "39092:39092"
    environment:
      CLUSTER_ID: 'vRSrPl6TRIusn12aG21giQ'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29092,2@kafka2:29093,3@kafka3:29094'
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka1:19092,EXTERNAL://kafka1:39092,CONTROLLER://kafka1:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:19092,EXTERNAL://kafka1:39092

      # PRPTOCOL settings
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin;User:client;User:controller;

      # Auth settings for SCRAM
      # Example:
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_SASL_ENABLED_MECHANISMS: PLAIN, SCRAM-SHA-256
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_<PLAIN_SASL or SCRAM-SHA-256>_JAAS_CONFIG: |
      #         org.apache.kafka.common.security.plain.PlainLoginModule required \
      #         username="admin" \
      #         password="admin-secret" \
      #         user_admin="admin-secret" \
      #         user_mds="mds-secret";

      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="controller" password="controller-secret" \
          user_controller="controller-secret";

      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_BROKER_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret" ;

      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret" ;

      KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS:
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # Need this for SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

    volumes:
      - kafka1-data:/var/lib/kafka/data
      - ./scripts/update_scram-sasl-plain_run.sh:/tmp/update.sh
      - ./clusterID:/tmp/clusterID
    command: "bash -c '/tmp/update.sh && /etc/confluent/docker/run'"

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "39093:39093"
    environment:
      CLUSTER_ID: 'vRSrPl6TRIusn12aG21giQ'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29092,2@kafka2:29093,3@kafka3:29094'
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka2:19093,EXTERNAL://kafka2:39093,CONTROLLER://kafka2:29093
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:19093,EXTERNAL://kafka2:39093

      # PRPTOCOL settings
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin;User:client;User:controller;

      # Auth settings for SCRAM
      # Example:
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_SASL_ENABLED_MECHANISMS: PLAIN, SCRAM-SHA-256
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_<PLAIN_SASL or SCRAM-SHA-256>_JAAS_CONFIG: |
      #         org.apache.kafka.common.security.plain.PlainLoginModule required \
      #         username="admin" \
      #         password="admin-secret" \
      #         user_admin="admin-secret" \
      #         user_mds="mds-secret";

      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="controller" password="controller-secret" \
          user_controller="controller-secret";

      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_BROKER_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret" ;

      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret";

      KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS:
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # Need this for SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

    volumes:
      - kafka2-data:/var/lib/kafka/data
      - ./scripts/update_scram-sasl-plain_run.sh:/tmp/update.sh
      - ./clusterID:/tmp/clusterID
    command: "bash -c '/tmp/update.sh && /etc/confluent/docker/run'"

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "39094:39094"
    environment:
      CLUSTER_ID: 'vRSrPl6TRIusn12aG21giQ'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29092,2@kafka2:29093,3@kafka3:29094'
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      KAFKA_METADATA_MAX_RETENTION_MS: 1200000
      KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: BROKER://kafka3:19094,EXTERNAL://kafka3:39094,CONTROLLER://kafka3:29094
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:19094,EXTERNAL://kafka3:39094

      # PRPTOCOL settings
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN

      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin;User:client;User:controller;

      # Auth settings for SCRAM
      # Example:
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_SASL_ENABLED_MECHANISMS: PLAIN, SCRAM-SHA-256
      # KAFKA_LISTENER_NAME_<LISTENER-NAME>_<PLAIN_SASL or SCRAM-SHA-256>_JAAS_CONFIG: |
      #         org.apache.kafka.common.security.plain.PlainLoginModule required \
      #         username="admin" \
      #         password="admin-secret" \
      #         user_admin="admin-secret" \
      #         user_mds="mds-secret";

      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="controller" password="controller-secret" \
          user_controller="controller-secret";

      KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_BROKER_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret" ;

      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-256_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required \
          username="admin" password="admin-secret" \
          user_admin="admin-secret" \
          user_connect="connect-secret" \
          user_schemaregistry="schemaregistry-secret" \
          user_ksqldb="ksqldb-secret" \
          user_tool="tool-secret" ;

      KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS:
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # Need this for SASL_PLAINTEXT
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

    volumes:
      - kafka3-data:/var/lib/kafka/data
      - ./scripts/update_scram-sasl-plain_run.sh:/tmp/update.sh
      - ./clusterID:/tmp/clusterID
    command: "bash -c '/tmp/update.sh && /etc/confluent/docker/run'"
volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: